#include <MemoryFree.h>
#include <TimeLib.h>
#include <DS1307RTC.h>
#include <EEPROM.h>
#include <LiquidCrystal.h>

#define AI_B1_CODE 785
#define AI_B2_CODE 853
#define AI_B3_CODE 930
#define AI_B4_CODE 1023

#define AI_ACCURACY 10

#define AI_DELAY 200

enum AI_BUTTONS { AI_B1, AI_B2, AI_B3, AI_B4 };

enum CHANNEL_MODE { CHANNEL_ON, CHANNEL_OFF, CHANNEL_TIMER };

#define MEMORY_CHANNEL_A_ADDR_HOUR_ON 0x10
#define MEMORY_CHANNEL_A_ADDR_MINUTE_ON 0x11
#define MEMORY_CHANNEL_A_ADDR_HOUR_OFF 0x12
#define MEMORY_CHANNEL_A_ADDR_MINUTE_OFF 0x13

#define MEMORY_CHANNEL_B_ADDR_HOUR_ON 0x14
#define MEMORY_CHANNEL_B_ADDR_MINUTE_ON 0x15
#define MEMORY_CHANNEL_B_ADDR_HOUR_OFF 0x16
#define MEMORY_CHANNEL_B_ADDR_MINUTE_OFF 0x17

#define MEMORY_CHANNEL_A_ADDR_HOUR_MODE 0x18
#define MEMORY_CHANNEL_B_ADDR_HOUR_MODE 0x19
